-- 1. Get number of monthly active customers.
SELECT *
FROM SAKILA.PAYMENT;
SELECT COUNT(DISTINCT CUSTOMER_ID)
FROM SAKILA.PAYMENT;
SELECT COUNT(*)
FROM SAKILA.PAYMENT;
SELECT CUSTOMER_ID, 
CONVERT(PAYMENT_DATE, DATE) AS PAYMENT_DATE,
DATE_FORMAT(CONVERT(PAYMENT_DATE, DATE), '%Y') AS PAYMENT_YEAR,
DATE_FORMAT(CONVERT(PAYMENT_DATE, DATE), '%M') AS PAYMENT_MONTH,
DATE_FORMAT(CONVERT(PAYMENT_DATE, DATE), '%m') AS PAYMENT_MONTH_NUMBER
FROM SAKILA.PAYMENT;

CREATE OR REPLACE VIEW SAKILA.ACTIVE_CUSTOMERS AS
SELECT CUSTOMER_ID, 
CONVERT(PAYMENT_DATE, DATE) AS PAYMENT_DATE,
DATE_FORMAT(CONVERT(PAYMENT_DATE, DATE), '%Y') AS PAYMENT_YEAR,
DATE_FORMAT(CONVERT(PAYMENT_DATE, DATE), '%M') AS PAYMENT_MONTH,
DATE_FORMAT(CONVERT(PAYMENT_DATE, DATE), '%m') AS PAYMENT_MONTH_NUMBER
FROM SAKILA.PAYMENT;

SELECT  PAYMENT_YEAR, PAYMENT_MONTH, PAYMENT_MONTH_NUMBER, COUNT(DISTINCT CUSTOMER_ID) AS ACTIVE_CUSTOMERS
FROM SAKILA.ACTIVE_CUSTOMERS
GROUP BY 1,2,3 ORDER BY 1,3 ASC;


CREATE OR REPLACE VIEW SAKILA.MONTHLY_ACTIVE_CUSTOMERS AS
SELECT  PAYMENT_YEAR, PAYMENT_MONTH, PAYMENT_MONTH_NUMBER, COUNT(DISTINCT CUSTOMER_ID) AS ACTIVE_CUSTOMERS
FROM SAKILA.ACTIVE_CUSTOMERS
GROUP BY 1,2,3 ORDER BY 1,3 ASC;

-- 2. Active users in the previous month.
SELECT 
  PAYMENT_YEAR,
  PAYMENT_MONTH,
  PAYMENT_MONTH_NUMBER,
  ACTIVE_CUSTOMERS AS CURRENT_MONTH_ACTIVE_CUSTOMERS,
  LAG(ACTIVE_CUSTOMERS, 1) OVER (ORDER BY PAYMENT_YEAR, PAYMENT_MONTH_NUMBER) AS PREVIOUS_MONTH_ACTIVE_CUSTOMERS
FROM
  SAKILA.MONTHLY_ACTIVE_CUSTOMERS
ORDER BY PAYMENT_YEAR, PAYMENT_MONTH_NUMBER;

-- 3. Percentage change in the number of active customers.
WITH CTE_MOM AS (
SELECT 
  PAYMENT_YEAR,
  PAYMENT_MONTH,
  PAYMENT_MONTH_NUMBER,
  ACTIVE_CUSTOMERS AS CURRENT_MONTH_ACTIVE_CUSTOMERS,
  LAG(ACTIVE_CUSTOMERS, 1) OVER (ORDER BY PAYMENT_YEAR, PAYMENT_MONTH_NUMBER) AS PREVIOUS_MONTH_ACTIVE_CUSTOMERS
FROM
  SAKILA.MONTHLY_ACTIVE_CUSTOMERS
ORDER BY PAYMENT_YEAR, PAYMENT_MONTH_NUMBER
)
SELECT *, 
((CURRENT_MONTH_ACTIVE_CUSTOMERS - PREVIOUS_MONTH_ACTIVE_CUSTOMERS) / PREVIOUS_MONTH_ACTIVE_CUSTOMERS) * 100 AS PERCENT_DIFF
FROM CTE_MOM;

-- 4. Retained customers every month.
WITH CTE_RETAINED AS (
	SELECT CUSTOMER_ID, DATE_FORMAT(PAYMENT_DATE, '%Y-%m') AS ACTIVE_MONTH
	FROM SAKILA.PAYMENT
)
SELECT 
	ACTIVE_MONTH, 
	COUNT(DISTINCT CUSTOMER_ID) AS RETAINED_CUSTOMERS_EVERY_MONTH
FROM CTE_RETAINED
GROUP BY ACTIVE_MONTH
ORDER BY ACTIVE_MONTH;